-- Insertion des salons
INSERT INTO salons (nom, ville, annee) VALUES
                                           ('JPO Lycée Saint Joseph', 'Toulouse', 2025),
                                           ('Salon InfoSup Toulouse', 'Toulouse', 2025),
                                           ('Forum des Lycées', 'Paris', 2024),
                                           ('Salon InnoTech', 'Lyon', 2026),
                                           ('JPO Lycée Sainte-Marie', 'Marseille', 2024);

-- Inscriptions pour le salon_id = 1
INSERT INTO inscriptions (nom, prenom, formation, ville, code_postal, email, telephone, sexe, statut, interet, origine_contact, salon_id) VALUES
                                                                                                                                              ('Petit', 'Maxime', 'BTS SAM', 'Balma', '51111', 'maxime.petit@mail.com', '0668996000', 'Homme', 'Étudiant', 'Cycle ingénieur', 'forum', 1),
                                                                                                                                              ('Girard', 'Alexis', 'Terminale Générale', 'Lyon', '65716', 'alexis.girard@mail.com', '0634480573', 'Homme', 'Apprenti', 'cycle-prepa', 'bouche', 1),
                                                                                                                                              ('Faure', 'Chloé', 'Licence Maths', 'Tournefeuille', '35579', 'chloé.faure@mail.com', '0634743876', 'Femme', 'Étudiant', 'Cycle ingénieur', 'reseaux', 1),
                                                                                                                                              ('Martin', 'Jules', 'Terminale Générale', 'Tournefeuille', '16421', 'jules.martin@mail.com', '0643607441', 'Homme', 'Étudiant', 'Cycle ingénieur', 'bouche', 1),
                                                                                                                                              ('Robert', 'Hugo', 'BTS BioAC', 'Tournefeuille', '35326', 'hugo.robert@mail.com', '0658817713', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 1),
                                                                                                                                              ('Lopez', 'Emma', 'DUT Informatique', 'Blagnac', '23164', 'emma.lopez@mail.com', '0641564074', 'Femme', 'Apprenti', 'cycle-prepa', 'site', 1),
                                                                                                                                              ('Durand', 'Enzo', 'BUT Informatique', 'Marseille', '62527', 'enzo.durand@mail.com', '0637630933', 'Homme', 'Étudiant', 'Cycle ingénieur', 'forum', 1),
                                                                                                                                              ('Petit', 'Camille', 'BUT GEII', 'Toulouse', '35215', 'camille.petit@mail.com', '0643567576', 'Femme', 'Étudiant', 'cycle-prepa', 'site', 1),
                                                                                                                                              ('Lefebvre', 'Julie', 'Licence Maths', 'Blagnac', '65020', 'julie.lefebvre@mail.com', '0631989509', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 1),
                                                                                                                                              ('Chevalier', 'Louis', 'BTS SIO', 'Muret', '41947', 'louis.chevalier@mail.com', '0638953432', 'Homme', 'Étudiant', 'Cycle ingénieur', 'autre', 1),
                                                                                                                                              ('Durand', 'Clara', 'BUT GEII', 'Colomiers', '44862', 'clara.durand@mail.com', '0628947604', 'Femme', 'Apprenti', 'cycle-prepa', 'site', 1),
                                                                                                                                              ('Roux', 'Sarah', 'Terminale Générale', 'Marseille', '40088', 'sarah.roux@mail.com', '0644992473', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 1),
                                                                                                                                              ('Dupont', 'Noah', 'BTS SAM', 'Paris', '61034', 'noah.dupont@mail.com', '0633041776', 'Homme', 'Étudiant', 'Cycle ingénieur', 'autre', 1),
                                                                                                                                              ('Morel', 'Inès', 'BUT Informatique', 'Colomiers', '49555', 'inès.morel@mail.com', '0645081894', 'Femme', 'Apprenti', 'cycle-prepa', 'forum', 1),
                                                                                                                                              ('Bernard', 'Nathan', 'BTS SIO', 'Muret', '21555', 'nathan.bernard@mail.com', '0679248844', 'Homme', 'Étudiant', 'cycle-prepa', 'site', 1);

-- Inscriptions pour salon_id = 2
INSERT INTO inscriptions (nom, prenom, formation, ville, code_postal, email, telephone, sexe, statut, interet, origine_contact, salon_id) VALUES
                                                                                                                                              ('Martin', 'Louis', 'BTS BioAC', 'Toulouse', '15346', 'louis.martin@mail.com', '0628439650', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 2),
                                                                                                                                              ('Petit', 'Julie', 'DUT Informatique', 'Colomiers', '15840', 'julie.petit@mail.com', '0610794403', 'Femme', 'Étudiant', 'cycle-prepa', 'bouche', 2),
                                                                                                                                              ('Morel', 'Lucas', 'BUT GEII', 'Paris', '58658', 'lucas.morel@mail.com', '0644438742', 'Homme', 'Étudiant', 'cycle-prepa', 'forum', 2),
                                                                                                                                              ('Robert', 'Emma', 'Licence Maths', 'Tournefeuille', '25598', 'emma.robert@mail.com', '0648884646', 'Femme', 'Étudiant', 'Cycle ingénieur', 'reseaux', 2),
                                                                                                                                              ('Faure', 'Noah', 'Terminale STI2D', 'Lyon', '62432', 'noah.faure@mail.com', '0640214532', 'Homme', 'Apprenti', 'cycle-prepa', 'forum', 2),
                                                                                                                                              ('Bernard', 'Anaïs', 'Terminale Générale', 'Marseille', '26091', 'anaïs.bernard@mail.com', '0629023730', 'Femme', 'Étudiant', 'cycle-prepa', 'site', 2),
                                                                                                                                              ('Durand', 'Thomas', 'BUT Informatique', 'Toulouse', '33792', 'thomas.durand@mail.com', '0632630071', 'Homme', 'Étudiant', 'Cycle ingénieur', 'reseaux', 2),
                                                                                                                                              ('Girard', 'Camille', 'BTS SAM', 'Muret', '54036', 'camille.girard@mail.com', '0626121743', 'Femme', 'Apprenti', 'cycle-prepa', 'site', 2),
                                                                                                                                              ('Chevalier', 'Maxime', 'DUT Informatique', 'Colomiers', '40113', 'maxime.chevalier@mail.com', '0627242463', 'Homme', 'Étudiant', 'Cycle ingénieur', 'autre', 2),
                                                                                                                                              ('Lopez', 'Léa', 'BTS SIO', 'Blagnac', '37176', 'léa.lopez@mail.com', '0667995894', 'Femme', 'Étudiant', 'cycle-prepa', 'forum', 2),
                                                                                                                                              ('Dupont', 'Hugo', 'Licence Maths', 'Lyon', '44562', 'hugo.dupont@mail.com', '0673349934', 'Homme', 'Étudiant', 'cycle-prepa', 'bouche', 2),
                                                                                                                                              ('Roux', 'Sarah', 'BTS SAM', 'Tournefeuille', '41806', 'sarah.roux@mail.com', '0673807863', 'Femme', 'Apprenti', 'Cycle ingénieur', 'reseaux', 2),
                                                                                                                                              ('Lefebvre', 'Nathan', 'BUT GEII', 'Marseille', '33644', 'nathan.lefebvre@mail.com', '0607873467', 'Homme', 'Étudiant', 'cycle-prepa', 'site', 2),
                                                                                                                                              ('Lemoine', 'Clara', 'BTS BioAC', 'Paris', '27855', 'clara.lemoine@mail.com', '0673081524', 'Femme', 'Étudiant', 'cycle-prepa', 'autre', 2),
                                                                                                                                              ('Durand', 'Jules', 'BTS SIO', 'Blagnac', '61885', 'jules.durand@mail.com', '0664400560', 'Homme', 'Étudiant', 'cycle-prepa', 'forum', 2);
INSERT INTO inscriptions (nom, prenom, formation, ville, code_postal, email, telephone, sexe, statut, interet, origine_contact, salon_id) VALUES
                                                                                                                                              ('Martin', 'Emma', 'BUT GEII', 'Paris', '25133', 'emma.martin@mail.com', '0605572426', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 3),
                                                                                                                                              ('Petit', 'Noah', 'Terminale Générale', 'Colomiers', '28654', 'noah.petit@mail.com', '0621103820', 'Homme', 'Étudiant', 'cycle-inge', 'forum', 3),
                                                                                                                                              ('Morel', 'Julie', 'Licence Maths', 'Toulouse', '54869', 'julie.morel@mail.com', '0601248397', 'Femme', 'Apprenti', 'cycle-prepa', 'autre', 3),
                                                                                                                                              ('Durand', 'Maxime', 'BTS SIO', 'Marseille', '27736', 'maxime.durand@mail.com', '0666477220', 'Homme', 'Étudiant', 'cycle-prepa', 'bouche', 3),
                                                                                                                                              ('Faure', 'Inès', 'DUT Informatique', 'Lyon', '27699', 'inès.faure@mail.com', '0622012200', 'Femme', 'Étudiant', 'cycle-inge', 'site', 3),
                                                                                                                                              ('Robert', 'Thomas', 'Terminale STI2D', 'Balma', '54594', 'thomas.robert@mail.com', '0641311575', 'Homme', 'Apprenti', 'cycle-prepa', 'forum', 3),
                                                                                                                                              ('Chevalier', 'Léa', 'BUT Informatique', 'Toulouse', '18942', 'léa.chevalier@mail.com', '0632872485', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 3),
                                                                                                                                              ('Girard', 'Lucas', 'BTS BioAC', 'Muret', '14987', 'lucas.girard@mail.com', '0635577780', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 3),
                                                                                                                                              ('Lopez', 'Clara', 'BTS SAM', 'Tournefeuille', '21635', 'clara.lopez@mail.com', '0624061677', 'Femme', 'Apprenti', 'cycle-prepa', 'forum', 3),
                                                                                                                                              ('Bernard', 'Alexis', 'Licence Maths', 'Blagnac', '40818', 'alexis.bernard@mail.com', '0662082282', 'Homme', 'Étudiant', 'cycle-inge', 'site', 3),
                                                                                                                                              ('Lefebvre', 'Manon', 'Terminale Générale', 'Marseille', '30642', 'manon.lefebvre@mail.com', '0650766593', 'Femme', 'Apprenti', 'cycle-prepa', 'reseaux', 3),
                                                                                                                                              ('Lemoine', 'Hugo', 'BUT GEII', 'Paris', '17191', 'hugo.lemoine@mail.com', '0644150745', 'Homme', 'Apprenti', 'cycle-prepa', 'bouche', 3),
                                                                                                                                              ('Durand', 'Camille', 'Terminale STI2D', 'Colomiers', '22115', 'camille.durand@mail.com', '0669117423', 'Femme', 'Étudiant', 'cycle-inge', 'site', 3),
                                                                                                                                              ('Dupont', 'Nathan', 'DUT Informatique', 'Toulouse', '19220', 'nathan.dupont@mail.com', '0664574984', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 3),
                                                                                                                                              ('Roux', 'Chloé', 'BUT Informatique', 'Blagnac', '62964', 'chloé.roux@mail.com', '0623649649', 'Femme', 'Apprenti', 'cycle-prepa', 'forum', 3);
INSERT INTO inscriptions (nom, prenom, formation, ville, code_postal, email, telephone, sexe, statut, interet, origine_contact, salon_id) VALUES
                                                                                                                                              ('Petit', 'Noah', 'BTS SIO', 'Lyon', '33017', 'noah.petit@mail.com', '0670034474', 'Homme', 'Apprenti', 'cycle-inge', 'autre', 4),
                                                                                                                                              ('Martin', 'Clara', 'DUT Informatique', 'Marseille', '50462', 'clara.martin@mail.com', '0629971078', 'Femme', 'Étudiant', 'cycle-prepa', 'forum', 4),
                                                                                                                                              ('Lopez', 'Maxime', 'BUT GEII', 'Colomiers', '46478', 'maxime.lopez@mail.com', '0603441211', 'Homme', 'Étudiant', 'cycle-prepa', 'reseaux', 4),
                                                                                                                                              ('Morel', 'Léa', 'Licence Maths', 'Blagnac', '34362', 'léa.morel@mail.com', '0676181516', 'Femme', 'Apprenti', 'cycle-prepa', 'site', 4),
                                                                                                                                              ('Durand', 'Lucas', 'BUT Informatique', 'Lyon', '51630', 'lucas.durand@mail.com', '0640905996', 'Homme', 'Étudiant', 'cycle-inge', 'forum', 4),
                                                                                                                                              ('Faure', 'Julie', 'BTS SAM', 'Balma', '27546', 'julie.faure@mail.com', '0663274575', 'Femme', 'Étudiant', 'cycle-prepa', 'bouche', 4),
                                                                                                                                              ('Bernard', 'Alexis', 'Terminale Générale', 'Muret', '24266', 'alexis.bernard@mail.com', '0678871947', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 4),
                                                                                                                                              ('Roux', 'Sarah', 'BTS BioAC', 'Toulouse', '30685', 'sarah.roux@mail.com', '0602835983', 'Femme', 'Apprenti', 'cycle-prepa', 'reseaux', 4),
                                                                                                                                              ('Robert', 'Jules', 'BUT GEII', 'Tournefeuille', '19612', 'jules.robert@mail.com', '0613141969', 'Homme', 'Étudiant', 'cycle-prepa', 'forum', 4),
                                                                                                                                              ('Chevalier', 'Emma', 'Licence Maths', 'Lyon', '14208', 'emma.chevalier@mail.com', '0625868047', 'Femme', 'Étudiant', 'cycle-prepa', 'site', 4),
                                                                                                                                              ('Lemoine', 'Nathan', 'BTS SIO', 'Toulouse', '25967', 'nathan.lemoine@mail.com', '0667449971', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 4),
                                                                                                                                              ('Girard', 'Camille', 'BUT Informatique', 'Paris', '63090', 'camille.girard@mail.com', '0661458031', 'Femme', 'Apprenti', 'cycle-prepa', 'forum', 4),
                                                                                                                                              ('Lefebvre', 'Thomas', 'Terminale Générale', 'Marseille', '26231', 'thomas.lefebvre@mail.com', '0674893750', 'Homme', 'Étudiant', 'cycle-inge', 'bouche', 4),
                                                                                                                                              ('Dupont', 'Chloé', 'BTS SAM', 'Blagnac', '40478', 'chloé.dupont@mail.com', '0641623796', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 4),
                                                                                                                                              ('Durand', 'Enzo', 'DUT Informatique', 'Colomiers', '17156', 'enzo.durand@mail.com', '0634816904', 'Homme', 'Étudiant', 'cycle-prepa', 'site', 4);
INSERT INTO inscriptions (nom, prenom, formation, ville, code_postal, email, telephone, sexe, statut, interet, origine_contact, salon_id) VALUES
                                                                                                                                              ('Petit', 'Camille', 'BTS SAM', 'Marseille', '62941', 'camille.petit@mail.com', '0629274973', 'Femme', 'Apprenti', 'cycle-prepa', 'forum', 5),
                                                                                                                                              ('Martin', 'Hugo', 'BUT GEII', 'Paris', '32689', 'hugo.martin@mail.com', '0612226815', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 5),
                                                                                                                                              ('Lopez', 'Clara', 'Terminale Générale', 'Blagnac', '31989', 'clara.lopez@mail.com', '0660721584', 'Femme', 'Étudiant', 'cycle-prepa', 'bouche', 5),
                                                                                                                                              ('Morel', 'Maxime', 'DUT Informatique', 'Colomiers', '13884', 'maxime.morel@mail.com', '0652935872', 'Homme', 'Étudiant', 'cycle-inge', 'site', 5),
                                                                                                                                              ('Durand', 'Inès', 'BUT Informatique', 'Lyon', '17174', 'inès.durand@mail.com', '0662369933', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 5),
                                                                                                                                              ('Faure', 'Lucas', 'BTS SIO', 'Marseille', '18206', 'lucas.faure@mail.com', '0664207267', 'Homme', 'Étudiant', 'cycle-prepa', 'autre', 5),
                                                                                                                                              ('Bernard', 'Julie', 'Licence Maths', 'Toulouse', '39499', 'julie.bernard@mail.com', '0663582101', 'Femme', 'Étudiant', 'cycle-prepa', 'site', 5),
                                                                                                                                              ('Roux', 'Louis', 'Terminale STI2D', 'Balma', '28748', 'louis.roux@mail.com', '0606599440', 'Homme', 'Apprenti', 'cycle-prepa', 'forum', 5),
                                                                                                                                              ('Robert', 'Sarah', 'BUT GEII', 'Marseille', '63713', 'sarah.robert@mail.com', '0608697583', 'Femme', 'Étudiant', 'cycle-prepa', 'reseaux', 5),
                                                                                                                                              ('Chevalier', 'Nathan', 'BTS BioAC', 'Tournefeuille', '23520', 'nathan.chevalier@mail.com', '0667159603', 'Homme', 'Étudiant', 'cycle-inge', 'bouche', 5),
                                                                                                                                              ('Lemoine', 'Chloé', 'BTS SAM', 'Paris', '31120', 'chloé.lemoine@mail.com', '0636233400', 'Femme', 'Apprenti', 'cycle-prepa', 'autre', 5),
                                                                                                                                              ('Girard', 'Thomas', 'BUT Informatique', 'Toulouse', '35810', 'thomas.girard@mail.com', '0677175143', 'Homme', 'Étudiant', 'cycle-prepa', 'forum', 5),
                                                                                                                                              ('Lefebvre', 'Léa', 'Licence Maths', 'Blagnac', '15388', 'léa.lefebvre@mail.com', '0638721547', 'Femme', 'Étudiant', 'cycle-prepa', 'site', 5),
                                                                                                                                              ('Dupont', 'Jules', 'Terminale Générale', 'Muret', '40445', 'jules.dupont@mail.com', '0612169736', 'Homme', 'Apprenti', 'cycle-prepa', 'reseaux', 5),
                                                                                                                                              ('Durand', 'Anaïs', 'DUT Informatique', 'Colomiers', '24876', 'anaïs.durand@mail.com', '0663937467', 'Femme', 'Étudiant', 'cycle-prepa', 'bouche', 5);

-- Inscriptions pour les autres salons...
-- [suite du script avec tous les 'Professeur' déjà remplacés par 'Autre' — identique à plus haut]

-- Utilisateurs
INSERT INTO utilisateurs (email, mot_de_passe, role) VALUES
    ('admin@isis.fr', 'motdepasse123', 'admin');
